class NotFoundError(Exception):
    pass


class InternalError(Exception):
    pass
